version: 0.1.0.{build}
image: Visual Studio 2019

init:
  - git config --global core.autocrlf false
branches:
  only:
    - master
skip_tags:  true
only_commits:
  files:
    - Shared/
    - Runtime/
    - Runtime.Standard/
    - appveyor.yml

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

before_build:
  - cmd: dotnet restore Runtime\Runtime.csproj
  - cmd: dotnet restore Runtime.Standard\Runtime.Standard.csproj
build:
  project: CI.sln
after_build:
  - cmd: 7z a ANTLRVisualizer.{version}.zip %APPVEYOR_BUILD_FOLDER%\Runtime\bin\Debug\*
  - cmd: 7z a ANTLRVisualizer.{version}.zip %APPVEYOR_BUILD_FOLDER%\Runtime.Standard\bin\Debug\*

artifacts:
  - path: ANTLRVisualizer.{version}.zip
    name: ANTLRVisualizer
  
deploy:
  - provider: GitHub
    description: ''
    auth_token:
      secure: aJaTRXIa+zc+SOGdNPKTH+znUun60Jh5b5pdjzLslhnoKk4vh1eoqO/vnGcDEwig
    artifact:
      ANTLRVisualizer
