version: 0.1.0.{build}

environment:
  matrix:
  
  - job_name: VS 2019 build
    appveyor_build_worker_image: Visual Studio 2019
    
  - job_name: VS 2017 build
    appveyor_build_worker_image: Visual Studio 2017

init:
  - git config --global core.autocrlf false
branches:
  only:
    - master
skip_tags:  true
only_commits:
  files:
    - Shared/
    - 2017/
    - 2019/
    - appveyor.yml

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

matrix:
  fast_finish: true

for:
- 
  matrix:
    only:
      - appveyor_build_worker_image: Visual Studio 2019

  configuration: ReleaseCI
  build:
    project: 2019\2019.csproj
  before_build:
  - cmd: dotnet restore 2019\2019.csproj
  artifacts:
    - path: 2019\bin\Debug
      type: zip
      name: ANTLRVisualizer2019

  deploy:
    - provider: GitHub
      description: ''
      auth_token:
        secure: aJaTRXIa+zc+SOGdNPKTH+znUun60Jh5b5pdjzLslhnoKk4vh1eoqO/vnGcDEwig
      artifact: ANTLRVisualizer2019

- 
  matrix:
    only:
      - appveyor_build_worker_image: Visual Studio 2017

  configuration: ReleaseCI2017
  build:
    project: 2017\2017.csproj
  before_build:
    - cmd: dotnet restore 2017\2017.csproj
  artifacts:
    - path: 2017\bin\Debug
      type: zip
      name: ANTLRVisualizer2017

  deploy:
    - provider: GitHub
      description: ''
      auth_token:
        secure: aJaTRXIa+zc+SOGdNPKTH+znUun60Jh5b5pdjzLslhnoKk4vh1eoqO/vnGcDEwig
      artifact: ANTLRVisualizer2017